### ISSUE TITLE
Error when reload resourcepack

### ISSUE THREAD

**Issue by Moirstral** [MrCrayfish/Framework#10]
Fabric 1.20.1
Mod version: 0.6.16
This error only occurs when changing resourcepack after exiting the title screen from the game.
```
[15:07:21] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Config property is not linked yet
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	...
Caused by: java.lang.IllegalStateException: Config property is not linked yet
	at com.mrcrayfish.framework.api.config.AbstractProperty.get(AbstractProperty.java:89) ~[framework-fabric-1.20.1-0.6.16.jar:?]
	at com.mrcrayfish.backpacked.util.ClientUtils.createBackpackTooltip(ClientUtils.java:23) ~[backpacked-fabric-1.20.1-2.2.7.jar:?]
	at com.mrcrayfish.backpacked.item.BackpackItem.method_7851(BackpackItem.java:62) ~[backpacked-fabric-1.20.1-2.2.7.jar:?]
	at net.minecraft.class_1799.method_7950(class_1799.java:647) ~[client-intermediary.jar:?]
	...
```

**Comment by MrCrayfish** [comment]
This is an issue with Backpacked that I still need to fix.
